### PR TITLE
added the new jsro guide

### PR DESCRIPTION
**Pull request by AishTron7**
Added the new job scheduling and resource optimisation guide

### CODE REVIEW

**Comment by alex-rosenberg35** [comment]
@AishTron7 Please fix the heading levels, unless you meant for everything to be under "Why Is My Job Not Running Yet?"

**Comment by alex-rosenberg35** [comment]
@AishTron7 Why do you have all these horizontal lines? Please remove them.

**Comment by alex-rosenberg35** [comment]
> Resources are assigned to accounts based on QOS (Quality of Service).

Uh, no. That's wrong. Did you have ChatGPT write this?

**Comment by alex-rosenberg35** [comment]
Aishwary  3:00 PM
No it was based on this https://slurm.schedmd.com/qos.html#limits I felt the QOS limits are controlling the resources for the account. But now that you point out, I faintly remember you saying that each account will be assigned resources manually? Anyways I got confused it seems

alexander.j.rosenberg  3:02 PM
Resources are assigned based on multiple factors. My understanding is that Fairshare is usually the main factor and QOS is more about imposing a cap on resources.

**Comment by alex-rosenberg35** [comment]
Please reword this:
> Be mindful of the tradeoff that comes with a higher QOS: while higher QoS levels allow longer runtimes, they may result in longer wait times due to lower scheduling priority.

There is no such thing as a "higher QOS". There are multiple types of limits that may be associated with a QOS, so referring to them as a higher or lower QOS doesn't really make sense or can be misleading. That is like referring to a certain type of food as a "higher food".

**Comment by alex-rosenberg35** [comment]
Aishwary 3:51 PM
sure, I’ll say long qos

alexander.j.rosenberg 3:55 PM
Also, please change the question "What Are Accounts?". It seems like a strange question that nobody would ask. Maybe something like "What are Slurm accounts?", or better yet "Are Slurm accounts the same thing as HPC accounts or Star user accounts?"

**Comment by alex-rosenberg35** [comment]
> Be aware of fairshare implications; consistently running long jobs can reduce your priority over time. Plan your submissions accordingly to balance resource usage.

That is due to the age factor, not fairshare.

**Comment by alex-rosenberg35** [comment]
I see you got the explanation of fairshare from one of the links I provided. That is why I said that link only does an "okay job" of introducing priority factors.

**Comment by manitofigh** [comment]
Hey @alex-rosenberg35 

I checked, fixed, and changed stuff I thought that could be improved. You can check my last 5 commits. I think it should be good to merge.

Nice work @AishTron7 !

**Comment by manitofigh** [comment]
The `--force` push was to override the typo in the commit. Sorry... my OCD kicked in.

**Pull request merged**
