### PR TITLE
NGC Pytorch container example

### PR DESCRIPTION
**Pull request by manitofigh**
- Instructions on how to setup NGC.
- Sample Python program to run within a Pytorch container.
- Sbatch script to run the Python program on a compute node.

### CODE REVIEW

**Comment by manitofigh** [comment]
Don't worry about the `--force-with-lease` on the latest commit on this branch. It was to re-write my earlier commit.

**Review by alex-rosenberg35 — CHANGES_REQUESTED** [review]
Please create a separate PR for [CSC-1652](http://jira.cs.hofstra.edu/browse/CSC-1652).

**Comment by manitofigh** [comment]
You said this one time it's fine when I was sitting next to your chair in 227...

**Comment by manitofigh** [comment]
| Original Feedback | Implementation Status |
|------------------|----------------------|
| Please change the actual name of the login node to a placeholder | ✅ Changed to `<login-node>` |
| Decouple it from the batch submission guide | ✅ Removed references to "Basic batch job example" |
| Put the content on SSH port forwarding into its own section | ✅ Created dedicated "SSH Port Forwarding" section with subsections |
| Add instructions on how to do SSH port forwarding through an Adams 204 machine | ✅ Added complete SSH tunnel command for Linux lab machines |
| Remind the user that the compute nodes themselves have no Internet access | ✅ Added reminder about file transfer through login node |
| Add a link on the submitting jobs guide to the new Jupyter Notebook page | ✅ Added link under "Interactive jobs" section |
| Briefly explain the use of srun for launching an interactive shell | ✅ Added "Working on the Same Node" section with `srun` command |
| Add a sentence about /home/<username>/ limitations | ✅ Added "Storage Space and Performance" section |
| Explain that additional packages can be installed through conda | ❌ will do this after the addition of the Condo page |
| Mention that using Docker images is also an option | ✅ Added Container Images section with Apptainer link at the bottom |
| Please confirm the example job script is actually tested and works as expected | ❓ I have to retry this as I previously only tested it with the VPN and not through the LL machines. |

**Pull request merged**
